models/Game.php
<?php

namespace app\models;

use Yii;
use yii\web\UploadedFile;

/**
 * This is the model class for table "games".
 *
 * @property integer $id
 * @property string $title
 * @property string $description
 * @property integer $users_id
 * @property string $cover
 * @property string $create_date
 * @property string $update_date
 *
 * @property Comments[] $comments
 * @property Users $users
 * @property Resources[] $resources
 */
class Game extends \yii\db\ActiveRecord
{
    private $coverFile;
    
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'games';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['title', 'description', 'users_id', 'create_date', 'update_date'], 'required'],
            [['description'], 'string'],
            [['users_id'], 'integer'],
            [['create_date', 'update_date'], 'safe'],
            [['title'], 'string', 'max' => 45],
            [['coverFile'], 'file', 'skipOnEmpty' => true, 'extensions' => 'png, jpg'],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'title' => 'Title',
            'description' => 'Description',
            'users_id' => 'Users ID',
            'cover' => 'Cover',
            'create_date' => 'Create Date',
            'update_date' => 'Update Date',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getComments()
    {
        return $this->hasMany(Comment::className(), ['games_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getUsers()
    {
        return $this->hasOne(User::className(), ['id' => 'users_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getResources()
    {
        return $this->hasMany(Resource::className(), ['games_id' => 'id']);
    }
    
    /**
    * set uploaded file as cover file of the game. Name of the file will be generate automatically but still maintaining file extension 
    * (for new cover) or use existing name if update cover
    */
    public function setCoverFile(UploadedFile $uploadedFile = null) {
        if(isset($uploadedFile)) {
            $this->coverFile = $uploadedFile;
            
            if(empty($this->cover)) {
                $date = new \DateTime();
                $this->cover = $date->format('YmdHis'). rand() . '.' . $this->coverFile->extension;
            }
            Yii::info("XXX file name: ".$this->cover);
        } else {
            Yii::info("XXX no file uploaded");
        }
    }
    
    public function getCoverFile() {
        return $this->coverFile;
    }
    
    /**
    * upload file to the designated directory
    */
    protected function upload() {
        $uploadSuccess = true;
        
        if(isset($this->coverFile)) {
            $uploadSuccess = $this->coverFile->saveAs(Yii::$app->basePath . DIRECTORY_SEPARATOR . 'web' . DIRECTORY_SEPARATOR . 'uploads'. DIRECTORY_SEPARATOR . $this->cover);
            if(!$uploadSuccess) {
                Yii::error("XXX Error while uploading file ", __METHOD__);
            }
        }
        
        return $uploadSuccess;
    }
    
    /**
    * delete cover file and all it's resources. Because once the game is deleted, all resource and comments automatically deleted
    */
    protected function deleteCoverAndResources() {
        if(isset($this->coverFile)) {
            $file = Yii::$app->basePath . DIRECTORY_SEPARATOR . 'web' . DIRECTORY_SEPARATOR . 'uploads'. DIRECTORY_SEPARATOR . $this->cover;
            if(file_exists($file)) {
                unlink($file);
            }
        }
        
        foreach($this->resources as $res) {
            $file = Yii::$app->basePath . DIRECTORY_SEPARATOR . 'web' . DIRECTORY_SEPARATOR . 'uploads'. DIRECTORY_SEPARATOR . $res->filename;
            if(file_exists($file)) {
                unlink($file);
            }
        }
    }
    
    public function beforeSave($insert) {
        if(parent::beforeSave($insert)) {
            // upload the file before saving data to database
            return $this->upload();
        }
        
        return false;
    }
    
    public function afterDelete() {
        // delete cover and resources after deleting game
        $this->deleteCoverAndResources();
        parent::afterDelete();
    }
}

controllers/GameController.php
<?php

namespace app\controllers;

use Yii;
use app\models\Game;
use app\models\Comment;
use app\models\Resource;
use yii\data\ActiveDataProvider;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii\web\UploadedFile;
use yii\helpers\VarDumper;
use yii\data\Pagination;

/**
 * GameController implements the CRUD actions for Game model.
 */
class GameController extends Controller
{
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['post'],
                ],
            ],
        ];
    }

    /**
     * Lists all Game models.
     * @return mixed
     */
    public function actionIndex()
    {
        $dataProvider = new ActiveDataProvider([
            'query' => Game::find(),
        ]);

        return $this->render('frontpage', [
            'dataProvider' => $dataProvider,
        ]);
    }
    
    public function actionMyGames() {
        if(!Yii::$app->user->can('createGame')) {
            throw new \yii\web\ForbiddenHttpException;
        }
        
        $userId = Yii::$app->user->id;
        
        $dataProvider = new ActiveDataProvider([
            'query' => Game::find()->where(['users_id' => $userId]),
        ]);
        
        return $this->render('index', [
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Game model.
     * @param integer $id
     * @return mixed
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
            'comment' => new Comment(),
        ]);
    }

    /**
     * Creates a new Game model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        if(!Yii::$app->user->can('createGame')) {
            throw new \yii\web\UnauthorizedHttpException;
        }
        
        $model = new Game();
        
        $isValid = $model->load(Yii::$app->request->post());
        $date = new \DateTime();
        $model->create_date = $date->format('Y-m-d');
        $model->update_date = $model->create_date;
        $model->users_id = Yii::$app->user->id; // only logged in usere can create new game
        
        $model->setCoverFile(UploadedFile::getInstance($model, 'cover'));
        
        if($isValid && !$model->validate()) {
            Yii::error('XXX Error while validating user input ', __METHOD__);
            $isValid = false;
        }
        
        if ($isValid && $model->save()) {
            $uploadedFiles = UploadedFile::getInstances($model, 'resources[filename]');
            foreach($uploadedFiles as $uf) {
                $resource = new Resource();
                $resource->games_id = $model->id;
                $resource->setResourceFile($uf);

                if($resource->validate()) {
                    $resource->save();
                }
            }
            
            return $this->redirect(['view', 'id' => $model->id]);
        } else {
            return $this->render('create', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Updates an existing Game model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);
        
        if(!Yii::$app->user->can('updateGame', ['game' => $model])) {
            throw new \yii\web\UnauthorizedHttpException;
        }
        
        $isValid = $model->load(Yii::$app->request->post());
        
        $date = new \DateTime();
        $model->update_date = $date->format('Y-m-d');
        
        $model->setCoverFile(UploadedFile::getInstance($model, 'cover'));
        
        $uploadedFiles = UploadedFile::getInstances($model, 'resources[filename]');
        foreach($uploadedFiles as $uf) {
            $resource = new Resource();
            $resource->games_id = $id;
            $resource->setResourceFile($uf);
            
            if($resource->validate()) {
                $isValid = $resource->save() && $isValid;
            }
        }
        
        if($isValid && !$model->validate()) {
            Yii::error("XXX Error while validating user input ", __METHOD__);
            $isValid = false;
        }

        if ($isValid && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        } else {
            return $this->render('update', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Deletes an existing Game model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     */
    public function actionDelete($id)
    {
        $game = $this->findModel($id);
        
        if(!Yii::$app->user->can('updateGame', ['game' => $game])) {
            throw new \yii\web\UnauthorizedHttpException;
        }
        
        if($game->delete()) {
            return $this->redirect(['index']);
        }
        
        return $this->goBack();
    }

    /**
     * Finds the Game model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Game the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Game::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }
    
    public function actionAddComment($id) {
        
        if(!Yii::$app->user->can('createComment')) {
            throw new \yii\web\ForbiddenHttpException;
        }
        
        $comment = new Comment();
        $isValid = $comment->load(Yii::$app->request->post());
        $comment->games_id = $id;
        $comment->users_id = Yii::$app->user->id;
        
        $date = new \DateTime();
        $comment->create_date = $date->format('Y-m-d');
        
        if($isValid && !$comment->validate()) {
            Yii::error("XXX Error while validating comment", __METHOD__);
            $isValid = false;
            
            $errors = $comment->getErrors();
            VarDumper::dump($errors);
            Yii::$app->end();
        }
        
        if($isValid && $comment->save()) {
            return $this->redirect(['view', 'id' => $id]);
        } else {
            Yii::error("XXX Error while saving comment");
            return $this->goBack();
        }
        
    }
    
    public function actionDeleteResource($id) {
        $resource = Resource::findOne($id);
        if($resource === null) {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
        
        if(!Yii::$app->user->can('updateGame', ['game' => $resource->games])) {
            throw new \yii\web\UnauthorizedHttpException;
        }
        
        $resource->delete();        
        return $this->redirect(['update', 'id' => $resource->games_id]);
    }
}

views/game/_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;
use yii\helpers\Url;

/* @var $this yii\web\View */
/* @var $model app\models\Game */
/* @var $form yii\widgets\ActiveForm */
?>
<div class="game-form">

    <?php $form = ActiveForm::begin(['options' => ['enctype' => 'multipart/form-data']]); ?>
    
    <?= $form->errorSummary($model); ?>

    <?= $form->field($model, 'title')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'description')->textarea(['rows' => 6]) ?>
    
    <?= $form->field($model, 'cover')->fileInput() ?>
    
    <h2>Resources</h2>
    <?= $form->field($model, 'resources[filename][]')->fileInput() ?>
    <?= $form->field($model, 'resources[filename][]')->fileInput() ?>
    <?= $form->field($model, 'resources[filename][]')->fileInput() ?>
    <?= $form->field($model, 'resources[filename][]')->fileInput() ?>
    <?= $form->field($model, 'resources[filename][]')->fileInput() ?>
    
    <?php if(count($model->resources) > 0) { ?>
    <div class="row">
        <div class="col-xs-6 col-md-3">
            <?php $resources = $model->resources; ?>
            <?php foreach($resources as $res) { ?>
                <div class="thumbnail"><img src="/uploads/<?= $res->filename ?>" /><a href="<?= Url::to(['game/delete-resource', 'id' => $res->id]) ?>"><span class="glyphicon glyphicon-remove text-danger" aria-hidden="true"></span></a></div>
            <?php } ?>
        </div>
    </div>
    <?php } ?>

    <div class="form-group">
        <?= Html::submitButton($model->isNewRecord ? 'Create' : 'Update', ['class' => $model->isNewRecord ? 'btn btn-success' : 'btn btn-primary', 'name' => 'game-button']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

views/game/create.php
<?php

use yii\helpers\Html;


/* @var $this yii\web\View */
/* @var $model app\models\Game */

$this->title = 'Create Game';
$this->params['breadcrumbs'][] = ['label' => 'Games', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="game-create">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

views/game/frontpage.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;
use yii\helpers\Url;
use yii\widgets\LinkPager;

/* @var $this yii\web\View */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Games';
$this->params['breadcrumbs'][] = $this->title;
?>
<div id="frontpage" class="game-index">    
    <div class="row">
        <?php foreach($dataProvider->getModels() as $game) { ?>
        <div class="col-xs-6 col-md-3">
            <div class="thumbnail">
                <img src="/uploads/<?= $game->cover ?>" alt="<?= $game->title ?>" />
                <h3><a href="<?= Url::to(['/game/view', 'id' => $game->id]) ?>"><?= Html::encode($game->title) ?></a></h3>
            </div>
        </div>
        <?php } ?>
    </div>
<!--
    <div class="grid">
        <?php foreach($dataProvider->getModels() as $game) { ?>
        <div class="grid-item">
            <div class="thumbnail">
                <img src="/uploads/<?= $game->cover ?>" alt="<?= $game->title ?>" />
                <h3><a href="<?= Url::to(['/game/view', 'id' => $game->id]) ?>"><?= Html::encode($game->title) ?></a></h3>
            </div>
        </div>
        <?php } ?>
    </div>
-->
    <?= LinkPager::widget([
        'pagination' => $dataProvider->pagination,
    ]) ?>
</div>

views/game/index.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;

/* @var $this yii\web\View */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Games';
$this->params['breadcrumbs'][] = ['label' => 'Games', 'url' => ['index']];
$this->params['breadcrumbs'][] = 'My Games';
?>
<div class="game-index">

    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?= Html::a('Create Game', ['create'], ['class' => 'btn btn-success']) ?>
    </p>

    <?= GridView::widget([
        'dataProvider' => $dataProvider,
        'columns' => [
            ['class' => 'yii\grid\SerialColumn'],

//            'id',
            'title',
            [
                'label' => 'Cover',
                'value' => function($data){
                    return "<img src='/uploads/".$data->cover."' class='img-responsive' width='200px' />";
                },
                'format' => 'html'
            ],
            'description:ntext',
//            'users_id',
            'create_date',
            // 'update_date',

            ['class' => 'yii\grid\ActionColumn'],
        ],
    ]); ?>

</div>

views/game/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\Game */

$this->title = 'Update Game: ' . ' ' . $model->title;
$this->params['breadcrumbs'][] = ['label' => 'Games', 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->title, 'url' => ['view', 'id' => $model->id]];
$this->params['breadcrumbs'][] = 'Update';
?>
<div class="game-update">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

views/game/view.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;
use yii\helpers\Url;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\Game */

$this->title = $model->title;
$this->params['breadcrumbs'][] = ['label' => 'Games', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="game-view">

    <h1><?= $model->title ?></h1>
    <div class="row">
        <div class="col-md-8">
            <div id="gallery">
            <?php foreach($model->resources as $resource) {
            ?>
                <div><img src="/uploads/<?= $resource->filename ?>" /></div>
            <?php
            } ?>
            </div>
        </div>
        <div id="game" class="col-md-4">
            <img src="/uploads/<?= $model->cover ?>" title="<?= $model->title ?>" class="img-responsive"/>
            <p class="description"><?= nl2br(Html::encode($model->description)) ?></p>
        </div>
    </div>
    
    <h2>Leave a Comment</h2>
    <?php if(!Yii::$app->user->isGuest) { ?>
    <div class="comment-form">
        <?php $form = ActiveForm::begin(['action' => ['game/add-comment', 'id' => $model->id]]); ?>
            <?= $form->errorSummary($comment); ?>
            <?= $form->field($comment, 'comment')->textarea(['rows' => 6])->label(false) ?>
            <div class="form-group">
                <?= Html::submitButton('Send', ['class' => 'btn btn-primary']) ?>
            </div>
        
        <?php ActiveForm::end(); ?>
    </div>
    <?php } else { ?>
        <a href="<?= Url::to('site/login') ?>">Login to Leave a Comment</a>
    <?php } ?>
    
    <h2>Comments</h2>
    <div class="row">
        <?php foreach($model->comments as $comment) { ?>
            <div class="comment col-md-8">
                <h4><?= $comment->users->name ?></h4>
                <em><?= $comment->create_date ?></em>
                <p><?= nl2br(Html::encode($comment->comment)) ?></p>
            </div>
        <?php } ?>
    </div>
    
    

</div>